### ISSUE TITLE
Can't set link flair

### ISSUE THREAD

**Issue by JROppenheimer** [SirCmpwn/RedditSharp#151]
With the following code I get a 403 forbidden error...

 I'm trying to set flair when submitting a post, I've tried every way I can think of and It gives me an error every time with this code:

[Code](http://i.imgur.com/XvYBwQ8.png)

The user is a mod and all subreddit settings seem correct, anybody got any idea what's going on?

Thanks

**Comment by SirTony** [comment]
I don't have time to fix it and send in a PR right now, but I've tracked down the issue.

It's being caused by [line 305 in Post.cs](https://github.com/SirCmpwn/RedditSharp/blob/3546f43087f7e666f74f6bdb7cf6b4c67db598e5/RedditSharp/Things/Post.cs#L305), the `Subreddit` field in the class is always null when creating a new link post in this fashion (I haven't tested other cases, it might just be null all the time). I suspect the API response has changed and [line 120](https://github.com/SirCmpwn/RedditSharp/blob/3546f43087f7e666f74f6bdb7cf6b4c67db598e5/RedditSharp/Things/Post.cs#L120) is not being properly populated from lines [36](https://github.com/SirCmpwn/RedditSharp/blob/3546f43087f7e666f74f6bdb7cf6b4c67db598e5/RedditSharp/Things/Post.cs#L36)/[42](https://github.com/SirCmpwn/RedditSharp/blob/3546f43087f7e666f74f6bdb7cf6b4c67db598e5/RedditSharp/Things/Post.cs#L42).

Temporary hackfix would be to hardcode line 305 and build a one-off version of the DLL for personal use only if it's an emergency. A permanent fix would be to either comb over the JSON response and see what's going on, or have the `Subreddit` class supply its name to the `Post` class when submitting a new linkpost or selfpost.
